README.md
metriq_gym/bench.py
metriq_gym/gates.py
metriq_gym/hardware/qv_clops_eplg_qiskit.py
metriq_gym/hardware/qv_clops_qiskit.py
metriq_gym/parse.py
poetry.lock
pyproject.toml

- Adding file `gate.py`for common gate-based utilities.
- Adding `bench.py` for common benchmarking runs (right not just Qrack)
- Adding `parse.py` for common command line parsing 
- Using `argparse` over `sys.argv` for cmd-line arg parsing
- Adding logging
- Updating `pyqrack` in `pyproject.toml` file. 
- Other misc. things (docstrings, comments, uniformizing style, etc.)

Modularizing for CLOPS and EPLG Qiskit Qrack benchmarking.

---

metriq_gym/bench.py

Removing noise adaptive transpile option as this is not supported on hardware runs.

Remove noise adaptive transpile option

---

metriq_gym/hardware/qv_clops_eplg_qiskit.py
metriq_gym/hardware/qv_clops_qiskit.py
metriq_gym/parse.py

This improves multi-trial benchmark reporting and adds the same functionality for XEB and EPLG.

Fix multi-trial benchmarks

---

metriq_gym/hardware/bell_experiment.py
metriq_gym/hardware/clops_benchmark.py

The IBM benchmark reference implementations are fully self-contained and licensed under Apache-2.0 License: 99% of the work to integrate them with metriq-gym, for now, appears to be just literally including the original files (with appropriate copyright and license notices).

IBM reference implementations

---

metriq_gym/metriq_metadata.py

Adding Metriq-ID to various devices, methods, and tasks for Metriq client.

Adding metriq metadata for client hookup.

---

README.md
pyproject.toml

Pin python version to 3.12 and emphasize in readme

---

.env.example
README.md
metriq_gym/dispatch_clops.py
metriq_gym/parse.py
metriq_gym/poll_clops.py
metriq_gym/poll_qv.py
poetry.lock
pyproject.toml

Adapting to pull IBM client token from .env.

---

.gitignore

Simplifying gitignore file.

---

.github/workflows/test.yml
pyproject.toml

Adding minimal workflow for tests

---

metriq_gym/poll_clops.py

Fixing CLOPS polling import

---

.github/workflows/test.yml
.pre-commit-config.yaml
README.md
poetry.lock
pyproject.toml

I want to set up some minimal type checking before creating the PRs for the refactoring of the dispatch/poll framework.
In this PR only an empty new folder is type checked, so the check is a trivial pass.

mypy initial setup

---

docs/assets/workflow-diagram.drawio

The one we used to generate the slide, in case anyone needs it and wants to modify it in the future.
The format is suitable for https://app.diagrams.net/

Workflow diagram raw file

---

.github/workflows/dependabot-automerge.yml

fix: automerge workflow

---

.github/dependabot.yml
.github/workflows/dependabot-automerge.yml

Auto-approve Dependabot PRs for patch releases of direct dependencies
Fixes #164

Auto-approve Dependabot PRs

---

metriq_gym/benchmarks/bseq.py

Fix for #227 
- The polling issue is now solved by properly serializing and deserializing the `GraphColoring` class object.

fix: chsh/bseq polling is now fixed

---

.github/workflows/test.yml

Add ability to automate tests over MacOS and Ubuntu.

test: add macos and ubuntu to test matrix

---

metriq_gym/benchmarks/__init__.py
metriq_gym/benchmarks/benchmark.py
metriq_gym/benchmarks/qml_kernel.py
metriq_gym/job_type.py
metriq_gym/schemas/examples/qml_kernel.example.json
metriq_gym/schemas/qml_kernel.schema.json
metriq_gym/task_helpers.py
poetry.lock

Pair-programmed with @Changhao-Li and @vprusso 
First working implementation of QML Kernel benchmark adapted from https://arxiv.org/abs/2405.09724
TODO: This implementation is single trial and the `trials` parameter is ignored for now. In a follow-up PR we will support multi-trial (with error calculation.)
Fixes #63 
Tested working on IBM Quantum 'sherbrooke' backend 🎉 
```sh
python metriq_gym/run.py dispatch metriq_gym/schemas/examples/qml_kernel.example.json --provider ibm --device ibm_sherbrooke
INFO - Starting job dispatch...
INFO - Dispatching QML Kernel benchmark job on ibm_sherbrooke device...
INFO - Job dispatched with ID: 31ea8e58-05af-4839-8e75-05eb9f1e0b4e
```
```sh
python metriq_gym/run.py poll --job_id 31ea8e58-05af-4839-8e75-05eb9f1e0b4e
INFO - Polling job... …
```

QML Kernel benchmark single-trial implementation

---

README.md
metriq_gym/cli.py
metriq_gym/helpers/execution_time.py
metriq_gym/job_manager.py
metriq_gym/run.py
tests/test_cli.py

It happens often that we want to know what the parameters of the job that we launched are, and this action allows the user to view that and other job details, without opening the file where we store this information.
Fixes #270 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

New action to view job details

---

metriq_gym/run.py

Fixes a bug introduced in #273

Fix prompt for job in poll action

---

README.md
metriq_gym/schemas/bseq.schema.json
metriq_gym/schemas/clops.schema.json
metriq_gym/schemas/qml_kernel.schema.json
metriq_gym/schemas/quantum_volume.schema.json
poetry.lock

Closes: #280 
- Enhances current benchmark schema files with JSON annotations for more specificity.

feat: enhance benchmark schemas with json annotations.

---

CITATION.cff

Closes: #279 
- Added `CITATION.cff` file generated via [CFFINIT](https://citation-file-format.github.io/cff-initializer-javascript/#/).

docs: add citation file.

---

README.md
poetry.lock
pyproject.toml

`python metriq_gym/run.py` --> the less verbose `mgym`.  (Proposed by @nathanshammah)
This works inside a Poetry shell and when pip installing the module (for now from local egg, and in the future from PyPI)
_Bonus_: switch to non-deprecated fields in pyproject.toml (checked with `poetry check`)
Running `mgym view` works as expected.

Short CLI command

---

.github/workflows/dependabot-automerge.yml

Unfortunately, these things are difficult to test directly (or at least I'm not aware of a good way to do so). 
This should (hopefully) resolve the broken automerge job in 
https://github.com/unitaryfoundation/metriq-gym/actions/runs/14775552610/job/41483057835

fix: automerge

---

README.md
metriq_gym/benchmarks/benchmark.py
metriq_gym/benchmarks/bseq.py
metriq_gym/benchmarks/clops.py
metriq_gym/benchmarks/qml_kernel.py
metriq_gym/benchmarks/quantum_volume.py
metriq_gym/cli.py
metriq_gym/exporters/base_exporter.py
metriq_gym/exporters/cli_exporter.py
metriq_gym/exporters/json_exporter.py
metriq_gym/run.py

JSON exporter feature, mostly to have a sense of how we want to aggregate all data we want to export and submit to external platforms.
By running `mgym poll --json`

Export benchmark result to json

---

poetry.lock
pyproject.toml

Details in https://github.com/unitaryfoundation/metriq-gym/issues/323#issuecomment-2940508017

Bump PyQrack to 1.53.1 mostly to fix builds

---

poetry.lock
pyproject.toml

Update qBraid version to support batched job submission for Azure devices.

chore: update qbraid version

---

poetry.lock
pyproject.toml

All tests seem to work out of the box with Qiskit 2.0, no code change required.

Add support for Qiskit 2

---

.github/workflows/publish-to-testpypi.yml

- Pointing test-pypi to correct location

fix: test-pypi release

---

.github/workflows/publish-to-pypi.yml

- Add workflow for adding to pypi release.

feat: add publish to pypi workflow

---

README.md

Adds pypi version and downloads shield to README. 
Also fix formatting of page title so it looks nicer on the pypi page.
Part of the #404 "epic"
Doc change
From the markdown preview of vscode

PyPi shields in readme

---

CITATION.cff

fix url in citation file

---

.env.example

The only thing required on our side to close #377
(Note .env.example is only used as a reference file.)
manual e2e test

Update credential template for IBM QP

---

README.md

Adding RTD badge in the `README.md` file for docs status/linking.

chore: add rtd badge

---

README.md
pyproject.toml

Set dev version

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-testpypi.yml
pyproject.toml

Going by the [plugin readme](https://github.com/mtkennerly/poetry-dynamic-versioning)

Fix dynamic versioning

---

README.md
docs/source/cli_workflows.rst
docs/source/end_to_end_tutorial.ipynb
docs/source/quickstart.rst
metriq_gym/benchmarks/wit.py
metriq_gym/constants.py
metriq_gym/registry.py
metriq_gym/schemas/examples/wit.example.json
metriq_gym/schemas/wit.schema.json
metriq_gym/suites/uf_frugal_3.json
tests/unit/quantinuum/test_run_fetch_result_quantinuum.py

chore: rename wormhole to wit

---

metriq_gym/exporters/base_exporter.py
metriq_gym/job_manager.py
metriq_gym/qplatform/device.py
metriq_gym/run.py
tests/unit/qplatform/test_device.py

Now the job export schema will include a subset of device metadata that are available across provider (num_qubits, device version, etc.)
Fixes #250 
Tested by dispatching, viewing, and uploading a job against the local simulator.
```bash
mgym job dispatch metriq_gym/schemas/examples/wit.example.json -p ibm -d ibm_fez
mgym job upload latest --dry-run
```

Report device metadata
