- poetry.lock
- pyproject.toml
- After updating a fork of the `tea-client` and making various updates to `metriq-client`, we can now add `metriq-client` as a project dependency without any dependency conflicts.
> Adding metriq-client as project dependency.

- README.md
- metriq_gym/bench.py
- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/hardware/clops_benchmark.py
- metriq_gym/poll_clops.py
- metriq_gym/poll_qv.py
- metriq_gym/process.py
Beware: this code has not been tested with an actual IBMQ account token!
This should split CLOPS benchmarks into separate dispatch and polling steps, without the need to keep a Python shell open. This works by retrieving the CLOPS benchmark job from cloud runtime services and "side-loading" it back into the benchmark-runner class when its status is `DONE`.
> Async CLOPS dispatch/polling

- .gitignore
- README.md
- metriq_gym/bench.py
- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/parse.py
- metriq_gym/process.py
- poetry.lock
- pyproject.toml
- Added dependencies to run bell_experiment (`matplotlib`, `qiskit_experiments`)
- Updated README to remove old examples
- Added `to_serializable` function for `BenchJobResult`. This was necessary as dispatching jobs to IBM would fail otherwise
- Update to polling of the IBM job result to process job number (otherwise this would fail when attempting to poll)
- Updates to dispatch calls for both QV and CLOPS to serialize result using the `to_serializable()` method that was added.
- Adding `.metriq_gym_jobs.json` to `.gitignore`.
> Fixing poll and dispatch for hardware jobs.

- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/parse.py
Minor tweak to allow the ability to specify the number of qubits for a given dispatch run:
```bash
python metriq_gym/dispatch_qv.py --shots 100 --backend ibm_nazca --trials 10 --n 7 --token  <TOKEN>
```
> Adding the ability to specify number of qubits via the command line

- metriq_gym/process.py
Jobs that are queued or still initializing don't get removed from the log file.
> Active non-running jobs back to job file

- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/poll_clops.py
Some miscellaneaous fixes to make the dispatch code run for CLOPS-type jobs.
Notes: 
1. Still not working against the Aer simulators (coming in a followup PR)
2. I am looking into fixing the polling part (also coming in a followup PR)
Testing:
```
python metriq_gym/dispatch_clops.py -n 2 --shots 10 --backend ibm_sherbrooke
```
> Fix dispatching CLOPS jobs

- .pre-commit-config.yaml
- README.md
- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/hardware/clops_benchmark.py
- metriq_gym/poll_clops.py
- poetry.lock
- pyproject.toml
Setting up Ruff (the same tool used in Mitiq), so we don't have to care about linting and formatting (new lines, unused vars, etc..) in each PR, and we can focus on the important things.
Notes:
- The Python version requirement introduced in https://github.com/unitaryfund/metriq-gym/pull/21 was too strict, I am now allowing patch versions of Python 3.12 – error was `Current Python version (3.12.7) is not allowed by the project (3.12).`  (cc @willzeng)
- After this PR is merged we should all install the pre-commit hook as specified in the README
- Files in `/metriq_gym/hardware` don't go through Ruff, because they are copied verbatim from https://github.com/qiskit-community/qiskit-device-benchmarking/ and the less we touch them, the easier it will be to keep them in sync with upstream …
> Ruff linter/formatter first setup

- .github/dependabot.yml
> Adding dependabot yaml file.

- .gitignore
- metriq_gym/bench.py
- metriq_gym/dispatch_clops.py
- metriq_gym/dispatch_qv.py
- metriq_gym/job_manager.py
- metriq_gym/parse.py
- metriq_gym/process.py
- poetry.lock
(this was pair programmed with @vprusso)
This is the first (of many) refactoring PRs post-QDC. We introduce a job log manager which will take care of saving asyncronous jobs to a db (at the moment a file.)
It makes everything more maintainable and readable since all the operations to the job log file will now be responsibility of the manager. It also allows to swap db to something else in the future without changing any another file than the one where the manager is defined.
This PR also introduces two concept of job id: 
- `provider_job_id`: an external job id, which is the one returned by the provider
- `id`: a metriq-gym internal id.
Note: at the moment the job log manager isn't thread-safe, but that's ok, since it's only used for single-user CLI operations.
> Introduce job log manager

- .github/workflows/test.yml
- metriq_gym/cli.py
- metriq_gym/dispatch_clops.py
- metriq_gym/schemas/clops.schema.json
- poetry.lock
- pyproject.toml
Closes #75
- CLOPS can now be run as part of the git submodule (instead of the previous `hardware/` dependency). For instance, once can now run the following
```
python metriq_gym/dispatch_clops.py metriq_gym/schemas/clops.schema.json --backend ibm_sherbrooke --provider ibmq
```
> Fix CLOPS submodule

- README.md
As we use a git submodule a user needs to clone the repo with a specific commend.
Our readme currently describes this instruction only in the contributing section at the end and not in the setup.
This PR also includes those instructions in the setup as it is needed for general users.
This is a documentation update.
> Update README.md to make recursive cloning clearer

- metriq_gym/process.py
- metriq_gym/run.py
Closes: #82
- The `run.py` file contains the main entry point for the program execution, so the logging format is instantiated there.
- The other place where `logging.basicConfig` was used is now removed.
> refactor: consolidate logger to main program entry point.

- metriq_gym/cli.py
This is a clean-up PR to remove CLI arguments leftover from old code. Benchmark-specific arguments are now passed via the schema instance file.
Fixes # (issue)
I couldn't find any place where those parameters were documented.
Run unit tests and smoke tested a dispatch/poll run.
> Remove cli arguments specific to benchmarks

- .github/workflows/dependabot-automerge.yml
- poetry.lock
- pyproject.toml
- Remove dependencies that are no longer used in the project
- ^ was checked with `deptry`, which is now a tool added to the project
- new GitHub action to auto-merge dependabot PR for patch updates (who are we kidding, none of us goes through the changelog anyway before approving those PRs!)
Fixes #164 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Improve dependency workflow

- .pre-commit-config.yaml
- README.md
- metriq_gym/provider.py
After [qBraid-SDK release v0.9.3](https://github.com/qBraid/qBraid/releases/tag/v0.9.3), we hadn't aligned the value of provider names with the keys in their entry-point. 
TODO: a shared solution (see draft's PR here: https://github.com/qBraid/qBraid/pull/890)
Fixes #215 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Align provider names with qBraid

- metriq_gym/benchmarks/benchmark.py
- metriq_gym/benchmarks/bseq.py
- metriq_gym/benchmarks/quantum_volume.py
- metriq_gym/run.py
- metriq_gym/topology_helpers.py
- tests/test_topology_helpers.py
- Extract functions specific to the device topology graph to a helper module
- Encapsulate results of benchmark in objects instead of printing them directly from poll handlers 
Tested dispatching of new jobs and polling existing jobs.
> Encapsulate benchmark results in objects

- README.md
- metriq_gym/cli.py
Make header of list-jobs table more explicit, and add docs on `poll` action without job_id flag.
Fixes #237 
Ran a `poll` and a `list-jobs` action to test.
> Tweak docs re:poll action

- metriq_gym/benchmarks/quantum_volume.py
Closes: #194 
Polling a QV job now yields:
```
QuantumVolumeResult(num_qubits=4, confidence_pass=True, xeb=1.289528214335571, hog_prob=1.0, hog_pass=True, eplg=0.06581394817600861, p_value=0.25, trials=2)
```
> feature: update qv with additional outputs

- README.md
- Alter prior "Example" section to be a general overview of the workflow
- Added explicit hardware and benchmark-specific example for running QV on IBM.
- Fix minor typos in README
> chore: update readme with specific example

- metriq_gym/exceptions.py
- metriq_gym/run.py
- tests/test_job_manager.py
- tests/test_run.py
- tests/test_schema_validator.py
Whenever the user mistypes the device name, a graceful error is shown, as well as a list of available devices, instead of an ugly stack-trace.
Fixing an issue that occurred during a demo to @rtvuser1
Fixes #258
```sh
metriq-gym-py3.12➜  ✗ python metriq_gym/run.py dispatch metriq_gym/schemas/examples/bseq.example.json --provider ibm --device ibm-nazca
INFO - Starting job dispatch...
ERROR - No device matching the name 'ibm-nazca' found in provider 'ibm'.
INFO - Devices available: ['ibm_brisbane', 'ibm_brussels', 'ibm_fez', 'ibm_kyiv', 'ibm_marrakesh', 'ibm_sherbrooke', 'ibm_strasbourg', 'ibm_torino']
```
> Fail gracefully when device is mistyped

- metriq_gym/benchmarks/quantum_volume.py
Closes: #248 
Based on [this comment](https://github.com/unitaryfund/metriq-gym/issues/248#issuecomment-2714824357), opting for the removal of the EPLG metadata output and calculation from quantum volume (QV).
> refactor: remove eplg from qv

- .pre-commit-config.yaml
Unfortunately, there is no automated way to keep the dependencies in sync (see comment in yaml file)
> Sync dependencies in precommit hook

- metriq_gym/benchmarks/benchmark.py
- metriq_gym/benchmarks/bseq.py
- metriq_gym/benchmarks/clops.py
- metriq_gym/benchmarks/qml_kernel.py
- metriq_gym/benchmarks/quantum_volume.py
It binds intermediate and result data-classes to generics, so we don't need to explicitly check the type of objects that are passed at runtime.
Fixes #266 
Running mypy
> Use generics in Benchmark class

- metriq_gym/circuits.py
- poetry.lock
- pyproject.toml
- tests/benchmarks/test_quantum_volume.py
Removes unused circuit conversion functions and consequently pytket dependencies that were preventing a critical security dependency update on Qiskit.
Fixes https://github.com/unitaryfund/metriq-gym/security/dependabot/7
run pytest
> Remove unused pytket dependencies

- .github/workflows/dependabot-automerge.yml
Closes: #308 
- `actions/checkout@v4` so the rebase action can update the branch.
- A rebase step that runs only if Dependabot’s metadata shows merge conflicts.
- The approve + auto-merge step remains gated on semver-patch updates.
> refactor: change so rebase can update branch

- metriq_gym/benchmarks/__init__.py
- metriq_gym/benchmarks/wormhole.py
- metriq_gym/job_type.py
- metriq_gym/schemas/examples/wormhole.example.json
- metriq_gym/schemas/wormhole.schema.json
Closes: #62 
- Adds the wormhole benchmark from [arXiv:2205.14081](https://arxiv.org/abs/2205.14081) as provided via the Python reference implementation by @nonhermitian. 
For instance, dispatching and polling on the `ibm_sherbrooke` device using the following configuration:
```
{
"benchmark_name": "Wormhole",
"num_qubits": 6,
"shots": 10
}
```
yields an expectation value outcome of:
```
WormholeResult(expectation_value=-0.6)
```
Note that the negative result is expected and means that the average over measurement shots is –0.6. This is expected if, for instance, about 80% of measurements yield the eigenvalue –1 (from |1⟩) and 20% yield +1 (from |0⟩). There is nothing inherently “wrong” with a negative expectation value—it just reflects the distribution of outcomes for your prepared …
> feat: add wormhole benchmark

- README.md
- metriq_gym/qplatform/__init__.py
- metriq_gym/qplatform/job.py
- metriq_gym/run.py
- tests/qplatform/test_job.py
This update introduces a provider‑agnostic utility for retrieving job status details, including queue position, and integrates it into the CLI.
- `JobStatusInfo` dataclass and `job_status` dispatcher centralize provider-specific status handling
- The CLI now displays each provider job’s status and queue position when polling incomplete jobs
- README example updated to show the new polling output with queue position details
- Module documentation notes that job metadata includes provider-specific queue information
fixes #238
> added status for jobs which are not completed #238

- metriq_gym/job_manager.py
- tests/test_job_manager.py
This PR addresses Issue [#301](https://github.com/unitaryfoundation/metriq-gym/issues/301) by improving the robustness of the `JobManager` when handling invalid entries in the input `.jsonl` file. Previously, such entries could lead to unhandled exceptions. This change ensures that invalid or malformed job entries are caught gracefully, preventing the entire job dispatch process from failing.
Fixes [#301](https://github.com/unitaryfoundation/metriq-gym/issues/301)
A test case has been added that includes a deliberately invalid JSONL entry to ensure the `JobManager` continues running without crashing. The behavior was verified locally, and the invalid entry is now skipped with a warning.
> lenient on handling invalid jsonl #301

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-testpypi.yml
Attempt to fix https://github.com/unitaryfoundation/metriq-gym/actions/runs/15908906894/job/44870967515
Now the checkout step is the same we use for the test workflow
> fix: fetch submodules in publish workflow

- metriq_gym/benchmarks/benchmark.py
- metriq_gym/benchmarks/clops.py
- metriq_gym/benchmarks/mirror_circuits.py
- metriq_gym/benchmarks/qml_kernel.py
- metriq_gym/benchmarks/quantum_volume.py
- metriq_gym/benchmarks/wormhole.py
- metriq_gym/helpers/task_helpers.py
- tests/unit/benchmarks/test_benchmark.py
- tests/unit/benchmarks/test_mirror_circuits.py
It was not intuitive for benchmarks developer that they were supposed to call the flatten_job_id functions. This makes the API more intuitive with a new way to construct an intermediate dataclass instance starting from a qBraid quantum job object.
This can be improved further, but it's a step forward imho.
Refactoring change
unit + e2e tests
> Hide details of provider ids flattening in framework

- .readthedocs.yaml
In order for RTD to work, we first need the `.readthedocs.yaml` file on the `main` branch:
> chore: add rtd yml config.

- README.md
This pull request addresses two minor issues in the README.md file to improve clarity and accuracy.
The schemas/examples/ directory's reference to bseq_example.json has been corrected to bseq.example.json to match the actual file name. Additionally, a missing space after the step number in the "Documentation" section (specifically "1.Navigate...") has been added for better formatting.
No dependencies are required for this change.
Fixes #452
This change involves only documentation (README.md) updates.
I have verified the changes locally by opening the README.md file in a Markdown viewer to confirm that the file path is now correct and the spacing after the step number is properly rendered.
> docs: Fix README typos (closes #452)

- metriq_gym/exporters/base_exporter.py
- metriq_gym/job_manager.py
- tests/unit/test_job_manager.py
Closes: #466 
- Pins the version number used to dispatch the job in the result output
- Added tests to ensure that when polling via different versions does not impact the dispatched version
> fix: version pinned to dispatch

- README.md
- metriq_gym/cli.py
- metriq_gym/exporters/base_exporter.py
- metriq_gym/exporters/dict_exporter.py
- metriq_gym/job_manager.py
- metriq_gym/run.py
- metriq_gym/suite_parser.py
- metriq_gym/suites/uf_frugal_3.json
- tests/e2e/test_dispatch_poll_job.py
- tests/e2e/test_dispatch_poll_suite.py
- tests/e2e/test_suite.json
- tests/unit/test_cli.py
- tests/unit/test_run.py
- tests/unit/test_suite_parser.py
Introduces support for managing and dispatching suites of benchmarks, including a new CLI subaction (`suite`) for all the existing actions (`dispatch`, `poll`, `view`) 
Note: this also deprecates the functionality to dispatched multiple benchmark jobs in one command, because that's now subsumed by dispatching a suite.
*CLI change*
The CLI command requires that the resource (`job` or `suite`) is specified, that is, instead of `mgym dispatch` it's now `mgym job dispatch` or `mgym suite dispatch`
Fixes #416 
TODO: specific tests for suite implementation to be added
> feat: Basic suite implementation

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-testpypi.yml
- README.md
- pyproject.toml
**Summary**
- Switches package versioning to be derived from Git tags at build time.
- Routes GitHub Release prereleases to TestPyPI and finals to PyPI.
- Documents the release process with tagging examples.
**Changes**
- pyproject.toml:
- Set `version = "0.0.0"` (managed by plugin).
- Added `[tool.poetry-dynamic-versioning]` with `enable = true`, `vcs = "git"`
, `style = "pep440"`.
- Workflows:
- `.github/workflows/publish-to-testpypi.yml`: install plugin; publish only wh
en `release.prerelease == true`.
- `.github/workflows/publish-to-pypi.yml`: install plugin; publish only when `
release.prerelease == false`.
- README:
- New “Release Process” section with SemVer tagging commands and CI routing.
**Rationale**
- Removes manual `pyproject.toml` version bumps.
on targets.
**CI Behavior**
- …
> feat: adding dynamic versioning

- metriq_gym/benchmarks/mirror_circuits.py
- metriq_gym/qplatform/device.py
- metriq_gym/registry.py
- metriq_gym/run.py
- metriq_gym/schemas/examples/mirror_circuits.example.json
- tests/unit/benchmarks/test_mirror_circuits.py
Addresses issue with Mirror Circuit benchmarks spotted by @Changhao-Li while trying to fetch results from hardware.
The expected bitstring against which the final result was checked happened to be the same for all the circuits, in case of protocol running with multiple random circuits.
Bonus:
- Fixes an issue with parsing the coupling map of IBM *fake* backends
- Fixes an issue with storing results introduced in #487
Fixes https://github.com/unitaryfoundation/metriq-gym-data/issues/2
It breaks polling of mirror circuits benchmark dispatched prior to this PR, which were not valid anyway.
Smoke testing against fake backends and real hardware + unit/e2e suite
> Fix averaging in mirror circuit benchmark

- .gitignore
- metriq_gym/__init__.py
- metriq_gym/job_manager.py
- pyproject.toml
- tests/unit/test_job_manager.py
Fixes version handling so that metriq-gym reports the correct Git-derived version both when installed from PyPI and when run directly from a git clone. Previously, the package version defaulted to 0.0.0 when used directly from a Git clone.
Tested dispatching a local job and now getting
```
│ app_version      │ 0.3.1.post5.dev0 
```
which is what we want
> Dynamic version in local dev environment

- metriq_gym/qplatform/device.py
- metriq_gym/quantinuum/device.py
- tests/unit/quantinuum/test_qplatform_device.py
There was not a proper dispatch in place for complete coupling maps for Quantinuum devices obtained via NEXUS.
Frustratingly, there is no programatic way in which to retrieve the number of qubits from a Quantinuum device on NEXUS:
https://docs.quantinuum.com/systems/trainings/getting_started/emulators.html
As a workaround, it's a standard that any H1-prefixed devices have 20-qubits and any H2-devices have 56.
> fix: Support complete graph-based benchmarks for quantinuum devices.

- metriq_gym/benchmarks/qedc_benchmarks.py
The goal of this PR is to fix the bug introduced in #542 involving an index out of range error. I first attempted to recreate the bug, but dispatching and polling the `bernstein-vazirani` benchmark on the `aer_simulator` worked smoothly ([recreate attempt](https://github.com/user-attachments/assets/d6a02e5e-70b4-43ff-bcf0-99fa36830be3)). However, I recalled that when we ran on a certain hardware provider, that not all of the circuits were executed. In this case, the loop in the `analyze_results()` method will have an index error -- it assumes that `counts_list` is the same length as `circuit_identifiers` (the number of counts matches the number of circuits sent for execution). 
The updated code does not make this assumption, and will only compute fidelities for the circuits that we have …
> Bug Fix: Index Out of Range Error
